version: '3.3'

services:
    medplan:
        build:
            context: .
            dockerfile: Dockerfile
        image: medplan:v1.0.0
        hostname: medplan
        container_name: medplan
        restart: always
        networks:
          - services_net
        ports:
          - 8081:8000

networks:
  services_net:

